package com.mentra.bluetoothsdk

data class WifiScanResult(
    val ssid: String,
    val requiresPassword: Boolean,
    val signalStrength: Int,
    val frequency: Int? = null,
) {
    internal fun toMap(): Map<String, Any> {
        val map =
            mutableMapOf<String, Any>(
                "ssid" to ssid,
                "requiresPassword" to requiresPassword,
                "signalStrength" to signalStrength,
            )
        frequency?.let { map["frequency"] = it }
        return map
    }

    companion object {
        internal fun fromMap(values: Map<String, Any>): WifiScanResult =
            WifiScanResult(
                ssid = stringValue(values, "ssid") ?: "",
                requiresPassword = boolValue(values, "requiresPassword") ?: false,
                signalStrength = numberValue(values, "signalStrength") ?: -1,
                frequency = numberValue(values, "frequency"),
            )
    }
}

internal data class GlassesStatus(
    val fullyBooted: Boolean,
    val connected: Boolean,
    val micEnabled: Boolean,
    val connectionState: GlassesConnectionState,
    val bluetoothClassicConnected: Boolean,
    val signalStrength: Int,
    val signalStrengthUpdatedAt: Long,
    val deviceModel: String,
    val androidVersion: String,
    val firmwareVersion: String,
    val besFirmwareVersion: String,
    val mtkFirmwareVersion: String,
    val bluetoothMacAddress: String,
    val leftMacAddress: String,
    val rightMacAddress: String,
    val macAddress: String,
    val buildNumber: String,
    val otaVersionUrl: String,
    val appVersion: String,
    val bluetoothName: String,
    val serialNumber: String,
    val style: String,
    val color: String,
    val wifi: WifiStatus,
    val batteryLevel: Int,
    val charging: Boolean,
    val caseBatteryLevel: Int,
    val caseCharging: Boolean,
    val caseOpen: Boolean,
    val caseRemoved: Boolean,
    val hotspot: HotspotStatus,
    val headUp: Boolean,
    val controllerConnected: Boolean,
    val controllerFullyBooted: Boolean,
    val controllerMacAddress: String,
    val controllerBatteryLevel: Int,
    val controllerSignalStrength: Int,
    val ringSignalStrength: Int,
) {
    internal fun toMap(): Map<String, Any> =
        mapOf(
            "connection" to connectionState.toStatusMap(connected, fullyBooted),
            "micEnabled" to micEnabled,
            "bluetoothClassicConnected" to bluetoothClassicConnected,
            "signalStrength" to signalStrength,
            "signalStrengthUpdatedAt" to signalStrengthUpdatedAt,
            "deviceModel" to deviceModel,
            "androidVersion" to androidVersion,
            "firmwareVersion" to firmwareVersion,
            "besFirmwareVersion" to besFirmwareVersion,
            "mtkFirmwareVersion" to mtkFirmwareVersion,
            "bluetoothMacAddress" to bluetoothMacAddress,
            "leftMacAddress" to leftMacAddress,
            "rightMacAddress" to rightMacAddress,
            "macAddress" to macAddress,
            "buildNumber" to buildNumber,
            "otaVersionUrl" to otaVersionUrl,
            "appVersion" to appVersion,
            "bluetoothName" to bluetoothName,
            "serialNumber" to serialNumber,
            "style" to style,
            "color" to color,
            "wifi" to wifi.toMap(),
            "batteryLevel" to batteryLevel,
            "charging" to charging,
            "caseBatteryLevel" to caseBatteryLevel,
            "caseCharging" to caseCharging,
            "caseOpen" to caseOpen,
            "caseRemoved" to caseRemoved,
            "hotspot" to hotspot.toMap(),
            "headUp" to headUp,
            "controllerConnected" to controllerConnected,
            "controllerFullyBooted" to controllerFullyBooted,
            "controllerMacAddress" to controllerMacAddress,
            "controllerBatteryLevel" to controllerBatteryLevel,
            "controllerSignalStrength" to controllerSignalStrength,
            "ringSignalStrength" to ringSignalStrength,
        )

    companion object {
        internal fun fromStoreMap(values: Map<String, Any>): GlassesStatus =
            GlassesStatus(
                fullyBooted = boolValue(values, "fullyBooted") ?: false,
                connected = boolValue(values, "connected") ?: false,
                micEnabled = boolValue(values, "micEnabled") ?: false,
                connectionState = GlassesConnectionState.fromValue(stringValue(values, "connectionState")),
                bluetoothClassicConnected = boolValue(values, "bluetoothClassicConnected") ?: false,
                signalStrength = numberValue(values, "signalStrength") ?: -1,
                signalStrengthUpdatedAt = longValue(values, "signalStrengthUpdatedAt") ?: 0L,
                deviceModel = stringValue(values, "deviceModel") ?: "",
                androidVersion = stringValue(values, "androidVersion") ?: "",
                firmwareVersion = stringValue(values, "firmwareVersion") ?: "",
                besFirmwareVersion = stringValue(values, "besFirmwareVersion") ?: "",
                mtkFirmwareVersion = stringValue(values, "mtkFirmwareVersion") ?: "",
                bluetoothMacAddress = stringValue(values, "bluetoothMacAddress") ?: "",
                leftMacAddress = stringValue(values, "leftMacAddress") ?: "",
                rightMacAddress = stringValue(values, "rightMacAddress") ?: "",
                macAddress = stringValue(values, "macAddress") ?: "",
                buildNumber = stringValue(values, "buildNumber") ?: "",
                otaVersionUrl = stringValue(values, "otaVersionUrl") ?: "",
                appVersion = stringValue(values, "appVersion") ?: "",
                bluetoothName = stringValue(values, "bluetoothName") ?: "",
                serialNumber = stringValue(values, "serialNumber") ?: "",
                style = stringValue(values, "style") ?: "",
                color = stringValue(values, "color") ?: "",
                wifi = WifiStatus.fromStoreMap(values) ?: WifiStatus.Disconnected,
                batteryLevel = numberValue(values, "batteryLevel") ?: -1,
                charging = boolValue(values, "charging") ?: false,
                caseBatteryLevel = numberValue(values, "caseBatteryLevel") ?: -1,
                caseCharging = boolValue(values, "caseCharging") ?: false,
                caseOpen = boolValue(values, "caseOpen") ?: true,
                caseRemoved = boolValue(values, "caseRemoved") ?: true,
                hotspot = HotspotStatus.fromStoreMap(values) ?: HotspotStatus.Disabled,
                headUp = boolValue(values, "headUp") ?: false,
                controllerConnected = boolValue(values, "controllerConnected") ?: false,
                controllerFullyBooted = boolValue(values, "controllerFullyBooted") ?: false,
                controllerMacAddress = stringValue(values, "controllerMacAddress") ?: "",
                controllerBatteryLevel = numberValue(values, "controllerBatteryLevel") ?: -1,
                controllerSignalStrength = numberValue(values, "controllerSignalStrength") ?: -1,
                ringSignalStrength = numberValue(values, "ringSignalStrength") ?: -1,
            )
    }
}

internal data class BluetoothStatus(
    val searching: Boolean,
    val searchingController: Boolean,
    val systemMicUnavailable: Boolean,
    val micEnabled: Boolean,
    val currentMic: String,
    val micRanking: List<String>,
    /**
     * Nearby glasses in stable discovery order. Existing entries keep their array position as
     * details refresh; new glasses append at the end, and removals should not reorder remaining
     * entries.
     */
    val searchResults: List<Device>,
    val wifiScanResults: List<WifiScanResult>,
    val lastLog: List<String>,
    val otherBtConnected: Boolean,
    val defaultWearable: String,
    val pendingWearable: String,
    val deviceName: String,
    val deviceAddress: String,
    val defaultController: String,
    val pendingController: String,
    val controllerDeviceName: String,
    val screenDisabled: Boolean,
    val preferredMic: String,
    val sensingEnabled: Boolean,
    val powerSavingMode: Boolean,
    val brightness: Int,
    val autoBrightness: Boolean,
    val dashboardHeight: Int,
    val dashboardDepth: Int,
    val headUpAngle: Int,
    val contextualDashboard: Boolean,
    val galleryModeAuto: Boolean,
    val buttonPhotoSize: ButtonPhotoSize,
    val buttonCameraLed: Boolean,
    val buttonMaxRecordingTime: Int,
    val buttonVideoWidth: Int,
    val buttonVideoHeight: Int,
    val buttonVideoFrameRate: Int,
    val shouldSendPcm: Boolean,
    val shouldSendLc3: Boolean,
    val shouldSendTranscript: Boolean,
    val bypassVad: Boolean,
    val offlineCaptionsRunning: Boolean,
    val localSttFallbackActive: Boolean,
    val shouldSendBootingMessage: Boolean,
) {
    val defaultDevice: Device?
        get() =
            defaultWearable.takeIf { it.isNotBlank() }?.let {
                Device(
                    model = DeviceModel.fromDeviceType(it),
                    name = deviceName,
                    address = deviceAddress.takeIf(String::isNotBlank),
                )
            }

    internal fun toMap(): Map<String, Any> =
        mapOf(
            "searching" to searching,
            "searchingController" to searchingController,
            "systemMicUnavailable" to systemMicUnavailable,
            "micEnabled" to micEnabled,
            "currentMic" to currentMic,
            "micRanking" to micRanking,
            "searchResults" to searchResults.map(Device::toMap),
            "wifiScanResults" to wifiScanResults.map { it.toMap() },
            "lastLog" to lastLog,
            "otherBtConnected" to otherBtConnected,
            "default_wearable" to defaultWearable,
            "pending_wearable" to pendingWearable,
            "device_name" to deviceName,
            "device_address" to deviceAddress,
            "default_controller" to defaultController,
            "pending_controller" to pendingController,
            "controller_device_name" to controllerDeviceName,
            "screen_disabled" to screenDisabled,
            "preferred_mic" to preferredMic,
            "sensing_enabled" to sensingEnabled,
            "power_saving_mode" to powerSavingMode,
            "brightness" to brightness,
            "auto_brightness" to autoBrightness,
            "dashboard_height" to dashboardHeight,
            "dashboard_depth" to dashboardDepth,
            "head_up_angle" to headUpAngle,
            "contextual_dashboard" to contextualDashboard,
            "galleryModeAuto" to galleryModeAuto,
            "button_photo_size" to buttonPhotoSize.value,
            "button_camera_led" to buttonCameraLed,
            "button_max_recording_time" to buttonMaxRecordingTime,
            "button_video_width" to buttonVideoWidth,
            "button_video_height" to buttonVideoHeight,
            "button_video_fps" to buttonVideoFrameRate,
            "should_send_pcm" to shouldSendPcm,
            "should_send_lc3" to shouldSendLc3,
            "should_send_transcript" to shouldSendTranscript,
            "bypass_vad" to bypassVad,
            "offline_captions_running" to offlineCaptionsRunning,
            "local_stt_fallback_active" to localSttFallbackActive,
            "shouldSendBootingMessage" to shouldSendBootingMessage,
        )

    companion object {
        internal fun fromStoreMap(values: Map<String, Any>): BluetoothStatus =
            BluetoothStatus(
                searching = boolValue(values, "searching") ?: false,
                searchingController = boolValue(values, "searchingController") ?: false,
                systemMicUnavailable = boolValue(values, "systemMicUnavailable") ?: false,
                micEnabled = boolValue(values, "micEnabled") ?: false,
                currentMic = stringValue(values, "currentMic") ?: "",
                micRanking = stringListValue(values, "micRanking"),
                searchResults =
                    mapListValue(values, "searchResults").mapNotNull(Device::fromMap),
                wifiScanResults =
                    mapListValue(values, "wifiScanResults").map(WifiScanResult::fromMap),
                lastLog = stringListValue(values, "lastLog"),
                otherBtConnected = boolValue(values, "otherBtConnected") ?: false,
                defaultWearable = stringValue(values, "default_wearable") ?: "",
                pendingWearable = stringValue(values, "pending_wearable") ?: "",
                deviceName = stringValue(values, "device_name") ?: "",
                deviceAddress = stringValue(values, "device_address") ?: "",
                defaultController = stringValue(values, "default_controller") ?: "",
                pendingController = stringValue(values, "pending_controller") ?: "",
                controllerDeviceName = stringValue(values, "controller_device_name") ?: "",
                screenDisabled = boolValue(values, "screen_disabled") ?: false,
                preferredMic = stringValue(values, "preferred_mic") ?: "auto",
                sensingEnabled = boolValue(values, "sensing_enabled") ?: true,
                powerSavingMode = boolValue(values, "power_saving_mode") ?: false,
                brightness = numberValue(values, "brightness") ?: 50,
                autoBrightness = boolValue(values, "auto_brightness") ?: true,
                dashboardHeight = numberValue(values, "dashboard_height") ?: 4,
                dashboardDepth = numberValue(values, "dashboard_depth") ?: 2,
                headUpAngle = numberValue(values, "head_up_angle") ?: 30,
                contextualDashboard = boolValue(values, "contextual_dashboard") ?: true,
                galleryModeAuto = boolValue(values, "galleryModeAuto") ?: true,
                buttonPhotoSize = ButtonPhotoSize.fromValue(stringValue(values, "button_photo_size")),
                buttonCameraLed = boolValue(values, "button_camera_led") ?: true,
                buttonMaxRecordingTime = numberValue(values, "button_max_recording_time") ?: 10,
                buttonVideoWidth = numberValue(values, "button_video_width") ?: 1280,
                buttonVideoHeight = numberValue(values, "button_video_height") ?: 720,
                buttonVideoFrameRate = numberValue(values, "button_video_fps") ?: 30,
                shouldSendPcm = boolValue(values, "should_send_pcm") ?: false,
                shouldSendLc3 = boolValue(values, "should_send_lc3") ?: false,
                shouldSendTranscript = boolValue(values, "should_send_transcript") ?: false,
                bypassVad = boolValue(values, "bypass_vad") ?: true,
                offlineCaptionsRunning = boolValue(values, "offline_captions_running") ?: false,
                localSttFallbackActive = boolValue(values, "local_stt_fallback_active") ?: false,
                shouldSendBootingMessage = boolValue(values, "shouldSendBootingMessage") ?: true,
            )
    }
}
